### ISSUE TITLE
Website menu disapears

### ISSUE THREAD

**Issue by icfly2** [mozilla/thimble.webmaker.org#1138]
A very silly bug, but with FF 40.0.3 win Windows 7 and 8 but not with Chrome the menu at the top right after signing in on https://thimble.mozilla.org/ is slightly below the Hi, USERNAME hover menu item such that the menu (Your projects, New projects, sign out) disappears if you try and select it unless you are very fast or have a touch screen.

**Comment by humphd** [comment]
I think @flukeout talked about this before, see https://github.com/mozilla/thimble.webmaker.org/issues/817.  I agree we should fix this, I'll do it.

**Comment by icfly2** [comment]
Yes I agree they concern the same issue. On my version of FF the website is practically not usable though because of this. In Chrome it works fine. Thus I would consider this a bug and not really something for enhancement.

The problem is the gap shown in the picture. The mouse has to pass it and as it does the menu disappears again. Sometimes there is a small delay in rendering this and then the mouse manages to jump across that gap and the menu can be used.

![thimblebug](https://cloud.githubusercontent.com/assets/7895513/10015234/09f252f2-6117-11e5-8c66-eda4d2ac1812.jpg)

**Comment by humphd** [comment]
This has been fixed, but we still need to push it to production.  @gideonthomas, can you do a prod push on Thimble next week so that https://github.com/mozilla/thimble.webmaker.org/pull/1141 gets picked up?  It's already on staging.

**Comment by icfly2** [comment]
I'm assuming this push hasn't happened yet? As the behavior still persists.Thanks for the quick response to the initial problem though.

**Comment by humphd** [comment]
Yeah, we haven't pushed this to production yet.  @gideonthomas, can you do a prod push on Thimble so we get this in?

**Comment by sedge** [comment]
Pushed to prod.

cc: @humphd

**Comment by humphd** [comment]
Great.  @icfly2 this may take ~1 day to actually update where you are (cache servers are good at caching things!).

**Comment by icfly2** [comment]
Awesome! Thanks for the great work.
